# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: book-catalog:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://s224169428_sit722_part2_g4nm_user:wGfMJ2U23A4AUUJU3VdLIWiy54sp4NcI@dpg-cr77u5bv2p9s73e9jef0-a.oregon-postgres.render.com/s224169428_sit722_part2_g4nm"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: NodePort
  selector:
    app: book-catalog
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30000

